name: Update to latest version of RangeMessage.xml
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download RangeMessage.xml
      run: curl -o RangeMessage.xml https://www.isbn-international.org/export_rangemessage.xml
    - name: Commit and push if changed
      run: |
        git diff --quiet RangeMessage.xml || {
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add RangeMessage.xml
          git commit -m "Update RangeMessage.xml"
          git push
        }
